create or replace function app_private.save_sale_draft_impl(
  p_sale_id uuid, p_expected_version bigint, p_customer_id uuid, p_sales_channel_id uuid,
  p_lines jsonb, p_order_discount text, p_note text, p_idempotency_key uuid
) returns jsonb language plpgsql security definer set search_path = '' as $$
declare v_actor uuid := (select auth.uid()); v_correlation uuid := gen_random_uuid(); v_id uuid := coalesce(p_sale_id, gen_random_uuid()); v_sale api.sales%rowtype; v_cached jsonb; v_result jsonb; v_order numeric(20,2); v_note text := app_private.empty_to_null(p_note);
begin
  if v_actor is null or not app_private.has_permission('sale.draft.manage') then return app_private.command_error('PERMISSION_DENIED','Bạn không có quyền lập hóa đơn nháp.',v_correlation); end if;
  if p_idempotency_key is null or jsonb_typeof(p_lines) <> 'array' or jsonb_array_length(p_lines) = 0 then return app_private.command_error('VALIDATION_FAILED','Giỏ hàng phải có ít nhất một sản phẩm.',v_correlation); end if;
  perform pg_advisory_xact_lock(hashtextextended(v_actor::text || ':sale.save:' || p_idempotency_key::text, 0)); select response into v_cached from app_private.command_deduplication where actor_id=v_actor and command_name='sale.save' and idempotency_key=p_idempotency_key; if found then return v_cached; end if;
  begin v_order:=p_order_discount::numeric; exception when others then return app_private.command_error('VALIDATION_FAILED','Giảm giá toàn đơn chưa đúng định dạng quốc tế.',v_correlation); end;
  if v_order<0 or not exists(select 1 from api.sales_channels c where c.id=p_sales_channel_id and c.is_active) then return app_private.command_error('VALIDATION_FAILED','Thông tin hóa đơn nháp chưa hợp lệ.',v_correlation); end if;
  if exists(select 1 from jsonb_to_recordset(p_lines) as x("productId" uuid,quantity text,"lineDiscountAmount" text,"lineOrder" integer) group by "productId" having count(*)>1) or exists(select 1 from jsonb_to_recordset(p_lines) as x("productId" uuid,quantity text,"lineDiscountAmount" text,"lineOrder" integer) left join api.products p on p.id=x."productId" left join app_private.product_sale_prices price on price.product_id=p.id and price.valid_to is null where p.id is null or not p.is_active or price.id is null) then return app_private.command_error('VALIDATION_FAILED','Có sản phẩm chưa hợp lệ, ngừng bán hoặc chưa có giá.',v_correlation); end if;
  if p_sale_id is null then insert into api.sales(id,customer_id,sales_channel_id,note,created_by,correlation_id) values(v_id,p_customer_id,p_sales_channel_id,v_note,v_actor,v_correlation); else select * into v_sale from api.sales where id=p_sale_id for update; if not found or v_sale.created_by<>v_actor or v_sale.status<>'DRAFT' then return app_private.command_error('INVALID_STATE','Không thể sửa hóa đơn nháp này.',v_correlation); end if; if p_expected_version is null or v_sale.version<>p_expected_version then return app_private.command_error('VERSION_CONFLICT','Hóa đơn nháp đã được cập nhật. Vui lòng tải lại.',v_correlation); end if; update api.sales set customer_id=p_customer_id,sales_channel_id=p_sales_channel_id,note=v_note,version=version+1,updated_at=now(),correlation_id=v_correlation where id=v_id; delete from api.sale_lines where sale_id=v_id; end if;
  insert into api.sale_lines(sale_id,product_id,product_name,sku,unit_name,quantity,unit_sale_price,gross_amount,line_discount_amount,net_amount,line_order) select v_id,p.id,p.name,p.sku,p.unit_name,x.quantity::numeric,price.sale_price,round(x.quantity::numeric*price.sale_price,2),coalesce(x."lineDiscountAmount",'0')::numeric,round(x.quantity::numeric*price.sale_price,2)-coalesce(x."lineDiscountAmount",'0')::numeric,x."lineOrder" from jsonb_to_recordset(p_lines) as x("productId" uuid,quantity text,"lineDiscountAmount" text,"lineOrder" integer) join api.products p on p.id=x."productId" join app_private.product_sale_prices price on price.product_id=p.id and price.valid_to is null;
  if exists(select 1 from api.sale_lines where sale_id=v_id and (quantity<=0 or line_discount_amount>gross_amount or line_discount_amount<0)) then return app_private.command_error('LINE_DISCOUNT_EXCEEDED','Giảm giá từng dòng không được vượt tiền hàng.',v_correlation); end if;
  if (v_order>0 or exists(select 1 from api.sale_lines where sale_id=v_id and line_discount_amount>0)) and not app_private.has_permission('sale.discount.apply') then return app_private.command_error('PERMISSION_DENIED','Bạn không có quyền áp dụng giảm giá.',v_correlation); end if;
  begin perform app_private.recalculate_sale_draft_impl(v_id,v_order); exception when others then return app_private.command_error('ORDER_DISCOUNT_EXCEEDED','Giảm giá toàn đơn vượt số tiền còn lại.',v_correlation); end;
  v_result:=app_private.command_success(jsonb_build_object('sale',app_private.sale_draft_json(v_id),'priceRefreshed',true),v_correlation); insert into app_private.command_deduplication(actor_id,command_name,idempotency_key,response) values(v_actor,'sale.save',p_idempotency_key,v_result); return v_result;
exception when invalid_text_representation or numeric_value_out_of_range then return app_private.command_error('VALIDATION_FAILED','Số lượng hoặc giảm giá chưa đúng định dạng quốc tế.',v_correlation); end;
$$;
